package model;
// Generated 21/12/2017 18:59:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FotoCardapio generated by hbm2java
 */
@Entity
@Table(name="foto_cardapio"
    ,catalog="dbrefeicao"
)
public class FotoCardapio  implements java.io.Serializable {


     private Integer idFotoCardapio;
     private byte[] foto;
     private String nomeFoto;
     private Set<Refeicao> refeicaos = new HashSet<Refeicao>(0);

    public FotoCardapio() {
    }

    public FotoCardapio(byte[] foto, String nomeFoto, Set<Refeicao> refeicaos) {
       this.foto = foto;
       this.nomeFoto = nomeFoto;
       this.refeicaos = refeicaos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_foto_cardapio", unique=true, nullable=false)
    public Integer getIdFotoCardapio() {
        return this.idFotoCardapio;
    }
    
    public void setIdFotoCardapio(Integer idFotoCardapio) {
        this.idFotoCardapio = idFotoCardapio;
    }

    
    @Column(name="foto")
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }

    
    @Column(name="nomeFoto", length=1000)
    public String getNomeFoto() {
        return this.nomeFoto;
    }
    
    public void setNomeFoto(String nomeFoto) {
        this.nomeFoto = nomeFoto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fotoCardapio")
    public Set<Refeicao> getRefeicaos() {
        return this.refeicaos;
    }
    
    public void setRefeicaos(Set<Refeicao> refeicaos) {
        this.refeicaos = refeicaos;
    }




}


