package model;
// Generated 21/12/2017 18:59:04 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Instituicao generated by hbm2java
 */
@Entity
@Table(name = "instituicao", catalog = "dbrefeicao"
)
public class Instituicao implements java.io.Serializable {

    private Integer idInstituicao;
    private Pessoa pessoa;
    private String nomeInst;
    private String emailInst;
    private String telefoneInst;
    private Set<Refeicao> refeicaos = new HashSet<Refeicao>(0);

    public Instituicao() {
    }

    public Instituicao(Pessoa pessoa, String nomeInst, String emailInst, String telefoneInst, Set<Refeicao> refeicaos) {
        this.pessoa = pessoa;
        this.nomeInst = nomeInst;
        this.emailInst = emailInst;
        this.telefoneInst = telefoneInst;
        this.refeicaos = refeicaos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_instituicao", unique = true, nullable = false)
    public Integer getIdInstituicao() {
        return this.idInstituicao;
    }

    public void setIdInstituicao(Integer idInstituicao) {
        this.idInstituicao = idInstituicao;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_pessoa")
    public Pessoa getPessoa() {
        return this.pessoa;
    }

    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    @Column(name = "nome_inst", length = 50)
    public String getNomeInst() {
        return this.nomeInst;
    }

    public void setNomeInst(String nomeInst) {
        this.nomeInst = nomeInst;
    }

    @Column(name = "email_inst", length = 100)
    public String getEmailInst() {
        return this.emailInst;
    }

    public void setEmailInst(String emailInst) {
        this.emailInst = emailInst;
    }

    @Column(name = "telefone_inst", length = 10)
    public String getTelefoneInst() {
        return this.telefoneInst;
    }

    public void setTelefoneInst(String telefoneInst) {
        this.telefoneInst = telefoneInst;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "instituicao")
    public Set<Refeicao> getRefeicaos() {
        return this.refeicaos;
    }

    public void setRefeicaos(Set<Refeicao> refeicaos) {
        this.refeicaos = refeicaos;
    }

    @Override
    public String toString() {
        return nomeInst;
    }

}
