package model;
// Generated 21/12/2017 18:59:04 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name = "pessoa", catalog = "dbrefeicao"
)
public class Pessoa implements java.io.Serializable {

    private Integer idPessoa;
    private String nome;
    private String telefone;
    private String email;
    private Set<Instituicao> instituicaos = new HashSet<Instituicao>(0);

    public Pessoa() {
    }

    public Pessoa(String nome, String telefone, String email, Set<Instituicao> instituicaos) {
        this.nome = nome;
        this.telefone = telefone;
        this.email = email;
        this.instituicaos = instituicaos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_pessoa", unique = true, nullable = false)
    public Integer getIdPessoa() {
        return this.idPessoa;
    }

    public void setIdPessoa(Integer idPessoa) {
        this.idPessoa = idPessoa;
    }

    @Column(name = "nome", length = 50)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "telefone", length = 10)
    public String getTelefone() {
        return this.telefone;
    }

    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    @Column(name = "email", length = 50)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
    public Set<Instituicao> getInstituicaos() {
        return this.instituicaos;
    }

    public void setInstituicaos(Set<Instituicao> instituicaos) {
        this.instituicaos = instituicaos;
    }

    @Override
    public String toString() {
        return nome;
    }

}
