package model;
// Generated 21/12/2017 18:59:04 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Refeicao generated by hbm2java
 */
@Entity
@Table(name="refeicao"
    ,catalog="dbrefeicao"
)
public class Refeicao  implements java.io.Serializable {


     private Integer idRefeicao;
     private FotoCardapio fotoCardapio;
     private Instituicao instituicao;
     private String tipoRef;
     private Date dataRef;
     private Date dataCadastro;
     private String nomeRef;
     private String descricao;

    public Refeicao() {
    }

    public Refeicao(FotoCardapio fotoCardapio, Instituicao instituicao, String tipoRef, Date dataRef, Date dataCadastro, String nomeRef, String descricao) {
       this.fotoCardapio = fotoCardapio;
       this.instituicao = instituicao;
       this.tipoRef = tipoRef;
       this.dataRef = dataRef;
       this.dataCadastro = dataCadastro;
       this.nomeRef = nomeRef;
       this.descricao = descricao;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_refeicao", unique=true, nullable=false)
    public Integer getIdRefeicao() {
        return this.idRefeicao;
    }
    
    public void setIdRefeicao(Integer idRefeicao) {
        this.idRefeicao = idRefeicao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_foto_cardapio")
    public FotoCardapio getFotoCardapio() {
        return this.fotoCardapio;
    }
    
    public void setFotoCardapio(FotoCardapio fotoCardapio) {
        this.fotoCardapio = fotoCardapio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_instituicao")
    public Instituicao getInstituicao() {
        return this.instituicao;
    }
    
    public void setInstituicao(Instituicao instituicao) {
        this.instituicao = instituicao;
    }

    
    @Column(name="tipo_ref", length=20)
    public String getTipoRef() {
        return this.tipoRef;
    }
    
    public void setTipoRef(String tipoRef) {
        this.tipoRef = tipoRef;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_ref")
    public Date getDataRef() {
        return this.dataRef;
    }
    
    public void setDataRef(Date dataRef) {
        this.dataRef = dataRef;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_cadastro", length=19)
    public Date getDataCadastro() {
        return this.dataCadastro;
    }
    
    public void setDataCadastro(Date dataCadastro) {
        this.dataCadastro = dataCadastro;
    }

    
    @Column(name="nome_ref", length=100)
    public String getNomeRef() {
        return this.nomeRef;
    }
    
    public void setNomeRef(String nomeRef) {
        this.nomeRef = nomeRef;
    }

    
    @Column(name="descricao", length=150)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
}


